const characters = [
  {
    name: 'Acheron',
    path: 'Nihility',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Argenti',
    path: 'Erudition',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 0 },
      { name: 'tactics', score: 0 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Arlan',
    path: 'Destruction',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Asta',
    path: 'Harmony',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 0 },
      { name: 'identity', score: 0 },
    ],
  },
  {
    name: 'Aventurine',
    path: 'Preservation',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Bailu',
    path: 'Abundance',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Black Swan',
    path: 'Nihility',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Blade',
    path: 'Destruction',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Boothill',
    path: 'The Hunt',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Bronya',
    path: 'Harmony',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Clara',
    path: 'Destruction',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Dan Heng',
    path: 'The Hunt',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Dr. Ratio',
    path: 'The Hunt',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Firefly',
    path: 'Destruction',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Fu Xuan',
    path: 'Preservation',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Gallagher',
    path: 'Abundance',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Gepard',
    path: 'Preservation',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Guinaifen',
    path: 'Nihility',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Hanya',
    path: 'Harmony',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Herta',
    path: 'Erudition',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Himeko',
    path: 'Erudition',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Hook',
    path: 'Destruction',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Huohuo',
    path: 'Abundance',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Jade',
    path: 'Erudition',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Jing Yuan',
    path: 'Erudition',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Jingliu',
    path: 'Destruction',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Kafka',
    path: 'Nihility',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Luka',
    path: 'Nihility',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Luocha',
    path: 'Abundance',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Lynx',
    path: 'Abundance',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'March 7th',
    path: 'Preservation',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Misha',
    path: 'Destruction',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Natasha',
    path: 'Abundance',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Pela',
    path: 'Nihility',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Qingque',
    path: 'Erudition',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Robin',
    path: 'Harmony',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Ruan Mei',
    path: 'Harmony',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Sampo',
    path: 'Nihility',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Seele',
    path: 'The Hunt',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Serval',
    path: 'Erudition',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Silver Wolf',
    path: 'Nihility',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Sparkle',
    path: 'Harmony',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Sushang',
    path: 'The Hunt',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Tingyun',
    path: 'Harmony',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Topaz and Numby',
    path: 'The Hunt',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Trailblazer',
    path: 'Destruction',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Welt',
    path: 'Nihility',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Xueyi',
    path: 'Destruction',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Yanqing',
    path: 'The Hunt',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Yukong',
    path: 'Harmony',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
];

const questions = [
  // Energy (Introverted: reverse true, Extraverted: reverse false)
  { text: "Do you prefer exploring the quiet, serene corners of the Herta Space Station over joining the lively crew gatherings?", trait: "energy", reverse: true },
  { text: "Would you rather spend time meditating alone in the Astral Express rather than participating in group strategy sessions?", trait: "energy", reverse: true },
  { text: "Do you often find solace in studying ancient relics in the Archives rather than leading a squad into battle?", trait: "energy", reverse: true },
  { text: "Do you thrive in the excitement of leading the charge in a Honkai beast hunt?", trait: "energy", reverse: false },
  { text: "Do you seek out social missions to connect with other factions across the galaxy?", trait: "energy", reverse: false },

  // Mind (Observant: reverse true, Intuitive: reverse false)
  { text: "Do you prefer meticulously analyzing battle data over dreaming up new combat techniques?", trait: "mind", reverse: true },
  { text: "Do you find satisfaction in mastering ancient weaponry rather than experimenting with futuristic gear?", trait: "mind", reverse: true },
  { text: "Do you often focus on the current status of your ship and crew rather than envisioning future alliances?", trait: "mind", reverse: true },
  { text: "Do you enjoy weaving complex strategies for uncharted territories and unknown enemies?", trait: "mind", reverse: false },
  { text: "Do you find excitement in speculating about the hidden powers of rare artifacts and their potential?", trait: "mind", reverse: false },

  // Nature (Thinking: reverse true, Feeling: reverse false)
  { text: "Do you value strategic precision over empathetic negotiations when dealing with interstellar disputes?", trait: "nature", reverse: true },
  { text: "Do you find it straightforward to give critical feedback to your team, even if it might be harsh?", trait: "nature", reverse: true },
  { text: "Do you prioritize logical outcomes over emotional bonds when making decisions about the crew's welfare?", trait: "nature", reverse: true },
  { text: "Do you often rely on your instincts and feelings when choosing allies for crucial missions?", trait: "nature", reverse: false },
  { text: "Do you believe maintaining harmony and trust among the crew is more important than strict protocol adherence?", trait: "nature", reverse: false },

  // Tactics (Judging: reverse true, Prospecting: reverse false)
  { text: "Do you meticulously plan your voyages, ensuring every detail is accounted for before departing the space dock?", trait: "tactics", reverse: true },
  { text: "Do you find satisfaction in completing mission objectives well ahead of schedule, with time for thorough debriefs?", trait: "tactics", reverse: true },
  { text: "Do you feel uneasy when mission parameters change unexpectedly, preferring a well-structured approach?", trait: "tactics", reverse: true },
  { text: "Do you embrace spontaneous detours to explore mysterious signals in deep space?", trait: "tactics", reverse: false },
  { text: "Do you find joy in discovering new opportunities and allies as they come, without rigid mission plans?", trait: "tactics", reverse: false },

  // Identity (Assertive: reverse true, Turbulent: reverse false)
  { text: "Do you maintain a steady course in leadership even when facing cosmic anomalies?", trait: "identity", reverse: true },
  { text: "Do you bounce back quickly from mission failures, learning and moving forward with renewed vigor?", trait: "identity", reverse: true },
  { text: "Do you have a clear understanding of your strengths and use them effectively during interstellar negotiations?", trait: "identity", reverse: true },
  { text: "Do you often find yourself doubting your decisions in critical moments, seeking reassurance from fellow commanders?", trait: "identity", reverse: false },
  { text: "Do you frequently feel anxious about the impression you make on high-ranking officials and alien diplomats?", trait: "identity", reverse: false }
];

function main() {
  const button = document.getElementById("start-button");

  button.addEventListener("click", function() {
    document.getElementById('home-container').style.display = 'none';
  });
}