const characters = [
  {
    name: 'Acheron',
    path: 'Nihility',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Argenti',
    path: 'Erudition',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 0 },
      { name: 'tactics', score: 0 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Arlan',
    path: 'Destruction',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Asta',
    path: 'Harmony',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 0 },
      { name: 'identity', score: 0 },
    ],
  },
  {
    name: 'Aventurine',
    path: 'Preservation',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Bailu',
    path: 'Abundance',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Black Swan',
    path: 'Nihility',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Blade',
    path: 'Destruction',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Boothill',
    path: 'The Hunt',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Bronya',
    path: 'Harmony',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Clara',
    path: 'Destruction',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Dan Heng',
    path: 'The Hunt',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Dr. Ratio',
    path: 'The Hunt',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Firefly',
    path: 'Destruction',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Fu Xuan',
    path: 'Preservation',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Gallagher',
    path: 'Abundance',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Gepard',
    path: 'Preservation',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Guinaifen',
    path: 'Nihility',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Hanya',
    path: 'Harmony',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Herta',
    path: 'Erudition',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Himeko',
    path: 'Erudition',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Hook',
    path: 'Destruction',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Huohuo',
    path: 'Abundance',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Jade',
    path: 'Erudition',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Jing Yuan',
    path: 'Erudition',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Jingliu',
    path: 'Destruction',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Kafka',
    path: 'Nihility',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Luka',
    path: 'Nihility',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Luocha',
    path: 'Abundance',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Lynx',
    path: 'Abundance',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'March 7th',
    path: 'Preservation',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Misha',
    path: 'Destruction',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Natasha',
    path: 'Abundance',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Pela',
    path: 'Nihility',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Qingque',
    path: 'Erudition',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Robin',
    path: 'Harmony',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Ruan Mei',
    path: 'Harmony',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Sampo',
    path: 'Nihility',
    type: 'Wind',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Seele',
    path: 'The Hunt',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Serval',
    path: 'Erudition',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Silver Wolf',
    path: 'Nihility',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Sparkle',
    path: 'Harmony',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Sushang',
    path: 'The Hunt',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Tingyun',
    path: 'Harmony',
    type: 'Lightning',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Topaz and Numby',
    path: 'The Hunt',
    type: 'Fire',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Trailblazer',
    path: 'Destruction',
    type: 'Physical',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Welt',
    path: 'Nihility',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Xueyi',
    path: 'Destruction',
    type: 'Quantum',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Yanqing',
    path: 'The Hunt',
    type: 'Ice',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
  {
    name: 'Yukong',
    path: 'Harmony',
    type: 'Imaginary',
    traits: [
      { name: 'energy', score: 1 },
      { name: 'mind', score: 1 },
      { name: 'nature', score: 1 },
      { name: 'tactics', score: 1 },
      { name: 'identity', score: 1 },
    ],
  },
];

export default characters;